### ISSUE TITLE
Blockmachine Validator

### ISSUE THREAD

**Issue by Megaduox** [bitsongofficial/delegation-program#88]
### Validator address

bitsongvaloper1f4z9xvfswjyss32d26z8v3ak5f97t74zj5c6ht

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Megaduox#5860/@DmitriKulagin/mailbox3087@gmail.com

### Application categories

Uptime, Participation in the BitSong ecosystem, None core development

### Details

**Uptime**: more than 98%
**Our Cosmos contributions**:

- Guide "How to create Bitsong Validator" for Russian-speaking community

Website: blockmachine.pro

### Goals

Automation of validation process, involvement of new people in the bitsong network

### Timetable

- Right now I'am writing telegram bot for governance monitoring on Python and bot for monitoring missed blocks for validators, I will make these bots even if the delegation is not wil be approved
- I'am author youtube channel about python-development and will make a video about Bitsong

**Comment by CommunityStaking** [comment]
Hi @Megaduox I'm missing a way for delegators to contact you either on chain or on your given website. Also the validator details are not present. Please update this. No need to give your uptime as we will use our monitoring system made by Felix to see what your uptime was during last epoch (or since your validator went live).

**Comment by ctrl-Felix** [comment]
Hi, could you maybe provide me the link to the  guide you created so that we can evaluate it?

**Comment by Megaduox** [comment]
Hi, of course here is the link
https://github.com/Block-machine/create_bitsong_validator

Пт, 26 авг. 2022 г. в 01:13, Felix ***@***.***>:

**Comment by Megaduox** [comment]
> Hi @Megaduox I'm missing a way for delegators to contact you either on chain or on your given website. Also the validator details are not present. Please update this. No need to give your uptime as we will use our monitoring system made by Felix to see what your uptime was during last epoch (or since your validator went live).

Hi @CommunityStaking , I Am added contact information on my website and validator details. Is everything ok?

**Comment by CommunityStaking** [comment]
Hi Megaduox, great about teh contact, however I still don't see the validator details filled when I check your validator on an for example mintscan: https://www.mintscan.io/bitsong/validators/bitsongvaloper1f4z9xvfswjyss32d26z8v3ak5f97t74zj5c6ht

**Comment by Megaduox** [comment]
> 

Done, I'm add link to mintscan and link in the main menu to validator details block

**Comment by Megaduox** [comment]
@CommunityStaking please check is everything ok?

**Comment by CommunityStaking** [comment]
Hi @Megaduox I'm still missing the details on chain
![Capture](https://user-images.githubusercontent.com/43610279/187530560-8e0809aa-5174-4504-8249-f0c81cb54644.PNG)

**Comment by Megaduox** [comment]
> Hi @Megaduox I'm still missing the details on chain. You can check out other validators what they have there. It's up to you of course what you want to promote there.
> 
> ![Capture](https://user-images.githubusercontent.com/43610279/187530560-8e0809aa-5174-4504-8249-f0c81cb54644.PNG)

@CommunityStaking , sorry 
Done! I thought it was about validator details on the website

**Comment by CommunityStaking** [comment]
All good now. No it was about the on chain data :)

**Comment by Megaduox** [comment]
Great, thanks!

Ср, 31 авг. 2022 г. в 15:17, CommunityStaking ***@***.***>:

**Comment by ctrl-Felix** [comment]
Score: 136
https://l.ctrl-felix.de/Yv072

**Comment by Megaduox** [comment]
> Score: 136 https://l.ctrl-felix.de/Yv072

@ctrl-Felix Hi, great! But our uptime is higher, it’s approx 98-99%, where you checked it?

**Comment by CommunityStaking** [comment]
> @ctrl-Felix Hi, great! But our uptime is higher, it’s approx 98-99%, where you checked it?

Hi @Megaduox your uptime is low because you did not run the full previous epoch (the uptimes are taken over the whole previous epoch). Assuming you will keep your uptime high it will count towards the next epoch.

**Comment by Megaduox** [comment]
Hi, great! But our uptime is higher, it’s approx 98-99%, where you checked
it?

Чт, 1 сент. 2022 г. в 00:52, Felix ***@***.***>:

**Comment by Megaduox** [comment]
Hi, glad you answered! Of course I will add contacts and update info about
my Validator details

Вс, 21 авг. 2022 г. в 22:28, CommunityStaking ***@***.***>:

**Comment by Megaduox** [comment]
Cool, thanks for explanation!





чт, 1 сент. 2022 г. в 12:17, CommunityStaking ***@***.***>:
